from PyQt5 import QtCore, QtGui, QtWidgets
from attendance import *
from operations import *
import shutil

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("Attendance Management System")
        MainWindow.resize(450, 455)
        MainWindow.setMinimumSize(QtCore.QSize(450, 455))
        MainWindow.setMaximumSize(QtCore.QSize(450, 455))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 445, 430))
        self.stackedWidget.setObjectName("stackedWidget")
        self.studenthome = QtWidgets.QWidget()
        self.studenthome.setObjectName("studenthome")
        self.gridLayoutWidget = QtWidgets.QWidget(self.studenthome)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 401, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 10, 0, 1, 1)
        self.add_student = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.add_student.setFont(font)
        self.add_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_student.setStyleSheet("border-color: rgb(170, 85, 255);")
        self.add_student.setObjectName("add_student")
        self.gridLayout.addWidget(self.add_student, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.teacher1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.teacher1.setFont(font)
        self.teacher1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.teacher1.setObjectName("teacher1")
        self.horizontalLayout_2.addWidget(self.teacher1, 0, QtCore.Qt.AlignHCenter)
        self.admin1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.admin1.setFont(font)
        self.admin1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admin1.setObjectName("admin1")
        self.horizontalLayout_2.addWidget(self.admin1, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_2.setIndent(-2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 11, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.view_attendance = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.view_attendance.setFont(font)
        self.view_attendance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.view_attendance.setObjectName("view_attendance")
        self.gridLayout.addWidget(self.view_attendance, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.studenthome)
        self.view_attend = QtWidgets.QWidget()
        self.view_attend.setObjectName("view_attend")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.view_attend)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 381, 391))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.student_name = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student_name.setFont(font)
        self.student_name.setObjectName("student_name")
        self.gridLayout_2.addWidget(self.student_name, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 8, 0, 1, 2)
        self.tableView = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 7, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.check_attendance = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.check_attendance.setFont(font)
        self.check_attendance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_attendance.setObjectName("check_attendance")
        self.gridLayout_2.addWidget(self.check_attendance, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.student2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student2.setFont(font)
        self.student2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.student2.setObjectName("student2")
        self.gridLayout_2.addWidget(self.student2, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.view_attend)
        self.admin_login = QtWidgets.QWidget()
        self.admin_login.setObjectName("admin_login")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.admin_login)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(40, 30, 341, 337))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setVerticalSpacing(27)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.admin_password = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.admin_password.setFont(font)
        self.admin_password.setObjectName("admin_password")
        self.gridLayout_3.addWidget(self.admin_password, 4, 1, 1, 1)
        self.admin_name = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.admin_name.setFont(font)
        self.admin_name.setObjectName("admin_name")
        self.gridLayout_3.addWidget(self.admin_name, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 7, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 2)
        self.admin_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.admin_btn.setFont(font)
        self.admin_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admin_btn.setObjectName("admin_btn")
        self.gridLayout_3.addWidget(self.admin_btn, 5, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.student3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student3.setFont(font)
        self.student3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.student3.setObjectName("student3")
        self.gridLayout_3.addWidget(self.student3, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.admin_login)
        self.admin_portal = QtWidgets.QWidget()
        self.admin_portal.setObjectName("admin_portal")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.admin_portal)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 381, 361))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.view_attendance_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.view_attendance_2.setFont(font)
        self.view_attendance_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.view_attendance_2.setObjectName("view_attendance_2")
        self.gridLayout_4.addWidget(self.view_attendance_2, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 7, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.add_student_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.add_student_2.setFont(font)
        self.add_student_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_student_2.setStyleSheet("border-color: rgb(170, 85, 255);")
        self.add_student_2.setObjectName("add_student_2")
        self.gridLayout_4.addWidget(self.add_student_2, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_20.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_20.setTextFormat(QtCore.Qt.RichText)
        self.label_20.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_20.setIndent(-2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 12, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 9, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.student4 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.student4.setFont(font)
        self.student4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.student4.setObjectName("student4")
        self.horizontalLayout_3.addWidget(self.student4, 0, QtCore.Qt.AlignHCenter)
        self.teacher2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.teacher2.setFont(font)
        self.teacher2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.teacher2.setObjectName("teacher2")
        self.horizontalLayout_3.addWidget(self.teacher2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 8, 0, 1, 1)
        self.stackedWidget.addWidget(self.admin_portal)
        self.admin_add_student = QtWidgets.QWidget()
        self.admin_add_student.setObjectName("admin_add_student")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.admin_add_student)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 0, 391, 421))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(21)
        self.gridLayout_5.setVerticalSpacing(19)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 13, 1, 1, 1)
        self.student_name_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student_name_2.setFont(font)
        self.student_name_2.setObjectName("student_name_2")
        self.gridLayout_5.addWidget(self.student_name_2, 5, 1, 1, 1)
        self.student_rollno = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student_rollno.setFont(font)
        self.student_rollno.setObjectName("student_rollno")
        self.gridLayout_5.addWidget(self.student_rollno, 6, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 9, 0, 1, 1)
        self.student_email = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student_email.setFont(font)
        self.student_email.setObjectName("student_email")
        self.gridLayout_5.addWidget(self.student_email, 7, 1, 1, 1)
        self.parent_name = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.parent_name.setFont(font)
        self.parent_name.setObjectName("parent_name")
        self.gridLayout_5.addWidget(self.parent_name, 8, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 7, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 0, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 5, 0, 1, 1)
        
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 8, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 10, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 6, 0, 1, 1)
        self.parent_email = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.parent_email.setFont(font)
        self.parent_email.setObjectName("parent_email")
        self.gridLayout_5.addWidget(self.parent_email, 9, 1, 1, 1)
        self.upload_file = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(11)
        font.setItalic(True)
        self.upload_file.setFont(font)
        self.upload_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload_file.setObjectName("upload_file")
        self.gridLayout_5.addWidget(self.upload_file, 10, 1, 1, 1)
        
        self.add_db = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.add_db.setFont(font)
        self.add_db.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_db.setObjectName("add_db")
        self.gridLayout_5.addWidget(self.add_db, 12, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.admin2 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.admin2.setFont(font)
        self.admin2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admin2.setObjectName("admin2")
        self.gridLayout_5.addWidget(self.admin2, 12, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.admin_add_student)
        self.admin_delete_student = QtWidgets.QWidget()
        self.admin_delete_student.setObjectName("admin_delete_student")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.admin_delete_student)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 0, 391, 416))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(21)
        self.gridLayout_6.setVerticalSpacing(26)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.student_name_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student_name_3.setFont(font)
        self.student_name_3.setObjectName("student_name_3")
        self.gridLayout_6.addWidget(self.student_name_3, 6, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 7, 0, 1, 1)
        self.del_student = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.del_student.setFont(font)
        self.del_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.del_student.setObjectName("del_student")
        self.gridLayout_6.addWidget(self.del_student, 9, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 0, 0, 1, 3)
        self.admin3 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.admin3.setFont(font)
        self.admin3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admin3.setObjectName("admin3")
        self.gridLayout_6.addWidget(self.admin3, 9, 0, 1, 1)
        self.student_email_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student_email_2.setFont(font)
        self.student_email_2.setObjectName("student_email_2")
        self.gridLayout_6.addWidget(self.student_email_2, 8, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 6, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 8, 0, 1, 1)
        self.student_rollno_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student_rollno_2.setFont(font)
        self.student_rollno_2.setObjectName("student_rollno_2")
        self.gridLayout_6.addWidget(self.student_rollno_2, 7, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 1, 0, 1, 3, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 13, 0, 1, 3)
        self.image_path_2 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.image_path_2.setText("")
        self.image_path_2.setObjectName("image_path_2")
        self.gridLayout_6.addWidget(self.image_path_2, 12, 0, 1, 1)
        self.stackedWidget.addWidget(self.admin_delete_student)
        self.teacher_portal = QtWidgets.QWidget()
        self.teacher_portal.setObjectName("teacher_portal")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.teacher_portal)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 10, 381, 411))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.gridLayout_7.addWidget(self.label_46, 7, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.gridLayout_7.addWidget(self.label_44, 5, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 9, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_7.addWidget(self.label_43, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_42.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_42.setTextFormat(QtCore.Qt.RichText)
        self.label_42.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_42.setIndent(-2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_7.addWidget(self.label_42, 10, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_7.addWidget(self.label_45, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 0, 0, 1, 1)
        self.add_student_3 = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.add_student_3.setFont(font)
        self.add_student_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_student_3.setStyleSheet("border-color: rgb(170, 85, 255);")
        self.add_student_3.setObjectName("add_student_3")
        self.gridLayout_7.addWidget(self.add_student_3, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.view_attendance_3 = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.view_attendance_3.setFont(font)
        self.view_attendance_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.view_attendance_3.setObjectName("view_attendance_3")
        self.view_attendance_3.clicked.connect(self.calculate_attendance)
        self.gridLayout_7.addWidget(self.view_attendance_3, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.student1 = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.student1.setFont(font)
        self.student1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.student1.setObjectName("student1")
        self.horizontalLayout.addWidget(self.student1, 0, QtCore.Qt.AlignHCenter)
        self.admin4 = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.admin4.setFont(font)
        self.admin4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admin4.setObjectName("admin4")
        self.horizontalLayout.addWidget(self.admin4, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_7.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.stackedWidget.addWidget(self.teacher_portal)
        self.teacher_email = QtWidgets.QWidget()
        self.teacher_email.setObjectName("teacher_email")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.teacher_email)

        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 391, 416))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(21)
        self.gridLayout_8.setVerticalSpacing(19)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.parent_email_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.parent_email_2.setFont(font)
        self.parent_email_2.setObjectName("parent_email_2")
        self.gridLayout_8.addWidget(self.parent_email_2, 8, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 7, 0, 1, 1)
        self.teacher3 = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.teacher3.setFont(font)
        self.teacher3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.teacher3.setObjectName("teacher3")
        self.gridLayout_8.addWidget(self.teacher3, 10, 0, 1, 1)
        self.student_rollno_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student_rollno_3.setFont(font)
        self.student_rollno_3.setObjectName("student_rollno_3")
        self.gridLayout_8.addWidget(self.student_rollno_3, 6, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_8.addWidget(self.label_49, 5, 0, 1, 1)
        self.add_db_4 = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.add_db_4.setFont(font)
        self.add_db_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_db_4.setObjectName("add_db_4")
        self.gridLayout_8.addWidget(self.add_db_4, 10, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_8.addWidget(self.label_50, 6, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_8.addWidget(self.label_53, 8, 0, 1, 1)
        self.student_name_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.student_name_4.setFont(font)
        self.student_name_4.setObjectName("student_name_4")
        self.gridLayout_8.addWidget(self.student_name_4, 5, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget_8)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_8.addWidget(self.textEdit, 9, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_8.addWidget(self.label_54, 9, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_8.addWidget(self.label_51, 13, 0, 1, 2)
        self.image_path_3 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.image_path_3.setText("")
        self.image_path_3.setObjectName("image_path_3")
        self.gridLayout_8.addWidget(self.image_path_3, 12, 0, 1, 2)
        self.parent_name_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.parent_name_2.setFont(font)
        self.parent_name_2.setObjectName("parent_name_2")
        self.gridLayout_8.addWidget(self.parent_name_2, 7, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 0, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.teacher_email)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.stackedWidget.setCurrentIndex(0)

        #     connect buttons
        self.add_student.clicked.connect(self.take_attendance)
        self.view_attendance.clicked.connect(self.view_attendance_page)
        self.check_attendance.clicked.connect(self.check_attendance_page)

        # self.admin_login.clicked.connect(self.admin_login_page)
        # ADMIN
        #     new student
        self.add_student_2.clicked.connect(self.add_student_page)
        #     delete student
        self.view_attendance_2.clicked.connect(self.delete_student_page)

        #     upload file
        self.upload_file.clicked.connect(self.upload_file_db)

        #   add new student
        self.add_db.clicked.connect(self.add_student_db)

        #     delete student
        self.del_student.clicked.connect(self.delete_student_db)

        #     add teacher
        self.add_student_3.clicked.connect(self.view_attendance_page)

        # email
        self.view_attendance_3.clicked.connect(self.email_page)

        #    send email
        self.add_db_4.clicked.connect(self.send_email_db)

       # student buttons
        self.student1.clicked.connect(self.student_back)
        self.student2.clicked.connect(self.student_back)
        self.student3.clicked.connect(self.student_back)
        self.student4.clicked.connect(self.student_back)

    #     admin buttons
        self.admin1.clicked.connect(self.admin_back)
        self.admin2.clicked.connect(self.admin_back)
        self.admin3.clicked.connect(self.admin_back)
        self.admin4.clicked.connect(self.admin_back)

    # teacher buttons
        self.teacher1.clicked.connect(self.teacher_back)
        self.teacher2.clicked.connect(self.teacher_back)
        self.teacher3.clicked.connect(self.teacher_back)

    def student_back(self):
        self.stackedWidget.setCurrentIndex(0)

    def admin_back(self):
        self.stackedWidget.setCurrentIndex(3)

    def teacher_back(self):
        self.stackedWidget.setCurrentIndex(6)

    def take_attendance(self):
        take_attendance()

    # open camera
    def view_attendance_page(self):
        self.stackedWidget.setCurrentIndex(1)

    def check_attendance_page(self):
        # self.stackedWidget.setCurrentIndex(1)
        # fetch details from excel
        data = get_dict()
        wb_obj = openpyxl.load_workbook(path)
        sheet_obj = wb_obj[datetime.now().strftime("%B")]
        roll_no = int(self.student_name.text())
        attendance_records = self.tableView
        for key, value in data.items():
            if roll_no in value:
                # Initialise tableview with headers
                attendance_records.setColumnCount(4)
                attendance_records.setRowCount(0)
                attendance_records.setHorizontalHeaderLabels(["Date", "In-time", "Out-time", "Hours"])
                # Insert data into tableview
                for i in range(3, sheet_obj.max_column+1):
                    cell = sheet_obj.cell(row=key, column=i)
                    if cell.value.startswith("In-time:"):
                        in_time = str(cell.value.split(' ')[1])
                        try:
                            out_time = cell.value.split(' ')[3]
                            hours = str((datetime.strptime(out_time, '%H:%M:%S') - datetime.strptime(in_time, '%H:%M:%S')).total_seconds()/3600)[:4]   
                        except:
                            out_time = "Unavailable"
                            hours = "-"
                        item_date = QtWidgets.QTableWidgetItem(get_col_name(i))
                        item_in_time = QtWidgets.QTableWidgetItem(in_time)
                        item_out_time = QtWidgets.QTableWidgetItem(out_time)
                        item_hours = QtWidgets.QTableWidgetItem(hours)
                        attendance_records.insertRow(attendance_records.rowCount())
                        attendance_records.setItem(attendance_records.rowCount()-1, 0, item_date)
                        attendance_records.setItem(attendance_records.rowCount()-1, 1, item_in_time)
                        attendance_records.setItem(attendance_records.rowCount()-1, 2, item_out_time)
                        attendance_records.setItem(attendance_records.rowCount()-1, 3, item_hours)
                    else:
                        # attendance_records.add_row([get_col_name(i), 'A', 'A', 0])
                        attendance_records.insertRow(attendance_records.rowCount())
                        attendance_records.setItem(attendance_records.rowCount()-1, 0, QtWidgets.QTableWidgetItem(get_col_name(i)))
                        attendance_records.setItem(attendance_records.rowCount()-1, 1, QtWidgets.QTableWidgetItem('A'))
                        attendance_records.setItem(attendance_records.rowCount()-1, 2, QtWidgets.QTableWidgetItem('A'))
                        attendance_records.setItem(attendance_records.rowCount()-1, 3, QtWidgets.QTableWidgetItem('0'))
                break
        else:
            attendance_records.setColumnCount(1)
            attendance_records.setRowCount(0)
            attendance_records.setHorizontalHeaderLabels(["No records found"])

    def calculate_attendance(self):
        calculate_attendance(get_dict())
    #     check database

    def admin_login_page(self):
        self.stackedWidget.setCurrentIndex(3)

    #     check database

    def add_student_page(self):
        self.stackedWidget.setCurrentIndex(4)
        

    def delete_student_page(self):
        self.stackedWidget.setCurrentIndex(5)

    def upload_file_db(self):
        fileDialog = QtWidgets.QFileDialog()
        fileDialog.setFileMode(QtWidgets.QFileDialog.AnyFile)
        fileDialog.setNameFilter("Images (*.jpg *.png *.jpeg)")
        fileDialog.setViewMode(QtWidgets.QFileDialog.Detail)
        if fileDialog.exec_():
            file_name = fileDialog.selectedFiles()[0]
            self.upload_file.setText(file_name)
            self.upload_file.setStyleSheet("color: green")
            self.upload_file.setEnabled(False)
        
    def add_student_db(self):
        name = self.student_name_2.text()
        parent_name = self.parent_name.text()
        email = self.student_email.text()
        rollno = self.student_rollno.text()
        parent_email = self.parent_email.text()
        student_photo = self.upload_file.text()
        error_dialog = QtWidgets.QMessageBox()
        error_dialog.setWindowTitle("Attendance System")
        if "" in {name, parent_name, email, rollno, parent_email, student_photo}:
            error_dialog.setIcon(QtWidgets.QMessageBox.Critical)
            error_dialog.setText("It seems like you have not filled all the fields. Please fill all the fields and try again.")
            error_dialog.exec_()
        else:
            imageName = rollno + '_' + name.replace(' ', '_')
            if imageName + '.png' in os.listdir('images') or imageName + '.jpg' in os.listdir('images'):
                error_dialog.setIcon(QtWidgets.QMessageBox.Information)
                error_dialog.setText("This student already exists. If you think this is an error, please contact the developer.")
                error_dialog.exec_()
            else:
                shutil.copy(student_photo, 'images/' + imageName + '.png')
                try:
                    workbook = openpyxl.load_workbook('Attendance.xlsx')
                    sheet = workbook['Details']
                    last_row = sheet.max_row
                    last_column = sheet.max_column
                    sheet.cell(row=last_row + 1, column=1).value = int(rollno)
                    sheet.cell(row=last_row + 1, column=2).value = name
                    sheet.cell(row=last_row + 1, column=3).value = email
                    sheet.cell(row=last_row + 1, column=4).value = parent_name
                    sheet.cell(row=last_row + 1, column=5).value = parent_email

                    for sheet_name in workbook.sheetnames:
                        if sheet_name == 'Details':
                            continue
                        sheet = workbook[sheet_name]
                        last_row = sheet.max_row
                        last_column = sheet.max_column
                        sheet.cell(row=last_row + 1, column=1).value = int(rollno)
                        sheet.cell(row=last_row + 1, column=2).value = name
                        for i in range(2, last_column + 1):
                            sheet.cell(row=last_row + 1, column=i).value = 'A'
                    workbook.save('Attendance.xlsx')
                    error_dialog.setIcon(QtWidgets.QMessageBox.Information)
                    error_dialog.setText('The student has been added successfully.')
                    error_dialog.exec_()
                except:
                    error_dialog.setIcon(QtWidgets.QMessageBox.Warning)
                    error_dialog.setText('Error in saving data.\nMust be the following reasons: \n1. Attendance.xlsx is not present in the current directory\n2. Attendance.xlsx is not in the correct format\n3. Roll number is not a number')
                    error_dialog.exec_()
        self.stackedWidget.setCurrentIndex(3)
                    
    def delete_student_db(self):
        print("delete student")

    def email_page(self):
        self.stackedWidget.setCurrentIndex(8)

    def send_email_db(self):
        self.stackedWidget.setCurrentIndex(9)

    #     send email to database

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_student.setText(_translate("MainWindow", "Take Attendance"))
        self.teacher1.setText(_translate("MainWindow", "Teacher"))
        self.admin1.setText(_translate("MainWindow", "Admin"))
        self.label.setText(_translate("MainWindow", " Attendance System"))
        self.label_2.setText(_translate("MainWindow", "Developed by Group Flip-flops    "))
        self.view_attendance.setText(_translate("MainWindow", "View Attendance"))
        self.label_10.setText(_translate("MainWindow", "View Attendance"))
        self.label_9.setText(_translate("MainWindow", "Developed By Group Flip-flops"))
        self.label_12.setText(_translate("MainWindow", "Enter roll number:"))
        self.check_attendance.setText(_translate("MainWindow", "Check"))
        self.student2.setText(_translate("MainWindow", "Back"))
        self.label_16.setText(_translate("MainWindow", "Enter roll number:"))
        self.label_14.setText(_translate("MainWindow", "Developed By Group Flip-flops"))
        self.label_13.setText(_translate("MainWindow", "Admin Login"))
        self.label_17.setText(_translate("MainWindow", "Enter password:"))
        self.admin_btn.setText(_translate("MainWindow", "Login"))
        self.student3.setText(_translate("MainWindow", "Student"))
        self.view_attendance_2.setText(_translate("MainWindow", "Delete Student"))
        self.label_23.setText(_translate("MainWindow", " Attendance System"))
        self.label_21.setText(_translate("MainWindow", "Welcome Admin"))
        self.add_student_2.setText(_translate("MainWindow", "Add Student"))
        self.label_20.setText(_translate("MainWindow", "Developed by Group Flip-flops    "))
        self.student4.setText(_translate("MainWindow", "Student"))
        self.teacher2.setText(_translate("MainWindow", "Teacher"))
        self.label_25.setText(_translate("MainWindow", "Developed by Group Flip-flops"))
        self.label_32.setText(_translate("MainWindow", "Parent email:"))
        self.label_27.setText(_translate("MainWindow", "Email:"))
        self.label_31.setText(_translate("MainWindow", "Add Student"))
        self.label_28.setText(_translate("MainWindow", "Name:"))
        self.label_30.setText(_translate("MainWindow", "Parent name:"))
        self.label_33.setText(_translate("MainWindow", "Student Photo:"))
        self.label_29.setText(_translate("MainWindow", "Roll number:"))
        self.upload_file.setText(_translate("MainWindow", "Upload picture"))
        self.add_db.setText(_translate("MainWindow", "Add Student"))
        self.admin2.setText(_translate("MainWindow", "Back"))
        self.label_39.setText(_translate("MainWindow", "Roll number:"))
        self.del_student.setText(_translate("MainWindow", "Delete"))
        self.admin3.setText(_translate("MainWindow", "Back"))
        self.label_34.setText(_translate("MainWindow", "Name:"))
        self.label_38.setText(_translate("MainWindow", "Email:"))
        self.label_36.setText(_translate("MainWindow", "Delete Student"))
        self.label_37.setText(_translate("MainWindow", "Developed by Group Flip-flops"))
        self.label_43.setText(_translate("MainWindow", "Welcome Teacher"))
        self.label_42.setText(_translate("MainWindow", "Developed by Group Flip-flops    "))
        self.label_45.setText(_translate("MainWindow", " Attendance System"))
        self.add_student_3.setText(_translate("MainWindow", "View Student Attendance"))
        self.view_attendance_3.setText(_translate("MainWindow", "Email Parent"))
        self.student1.setText(_translate("MainWindow", "Student"))
        self.admin4.setText(_translate("MainWindow", "Admin"))
        self.label_47.setText(_translate("MainWindow", "Parent name:"))
        self.teacher3.setText(_translate("MainWindow", "Back"))
        self.label_49.setText(_translate("MainWindow", "Name:"))
        self.add_db_4.setText(_translate("MainWindow", "Send Email"))
        self.label_50.setText(_translate("MainWindow", "Name of student:"))
        self.label_53.setText(_translate("MainWindow", "Parent email:"))
        self.label_54.setText(_translate("MainWindow", "Issue / Reason:"))
        self.label_51.setText(_translate("MainWindow", "Developed by Group Flip-flops"))
        self.label_52.setText(_translate("MainWindow", "Email"))
            
            
import sys
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
